version: "3"
services:
  bitcoind:
    platform: linux/x86_64
    build: "./bitcoind"
    volumes:
      - "./bitcoind/.data/bitcoind:/home/user/.bitcoind"
    restart: always
  alice:
    platform: linux/x86_64
    build: "./lnd"
    ports:
      - "10009:10009"
    volumes:
      - "./lnd/.data/alice-lnd:/home/user/.lnd"
