version: "3"
services:
  bitcoind:
    platform: linux/x86_64
    build: "./bitcoind"
    volumes:
      - "./bitcoind/.data/bitcoind:/home/user/.bitcoind"
    restart: always
  alice:
    platform: linux/x86_64
    build: "./lnd"
    volumes:
      - "./lnd/.data/alice-lnd:/home/user/.lnd"
  nginx:
    image: nginx:1.19
    ports:
      - "20080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
